### ISSUE TITLE
Generate CRUD not working with 4.4.0

### ISSUE THREAD

**Issue by andre-artus** [EasyAbp/AbpHelper.CLI#150]
It appears the `abphelper generate crud` (version 0.8.1)  does not work against ABP 4.4.0:

Some file names and the folder structure seems to have changed between 4.3.0 and 4.4.0, leading the `generate crud` command to fail with an `System.IO.FileNotFoundException`.

**Comment by desconfiado** [comment]
Same here.

`abphelper generate crud Unit -d D:\Temp\VSProjects\TodoApp
[17:15:58 INF] Use directory: `D:\Temp\VSProjects\TodoApp`
[17:15:59 INF] Command 'crud' started.
[17:16:00 DBG] ProjectInfoProviderStep Input [baseDirectory]: 'D:\Temp\VSProjects\TodoApp'
[17:16:00 DBG] ProjectInfoProviderStep Input [excludeDirectories]:
[17:16:00 DBG] ProjectInfoProviderStep Output [projectInfo]: 'BaseDirectory: D:\Temp\VSProjects\TodoApp, FullName: TodoApp, Name: TodoApp, TemplateType: Application, UiFramework: RazorPages, Tiered: False'
[17:16:00 DBG] FileFinderStep Input [baseDirectory]: 'D:\Temp\VSProjects\TodoApp'
[17:16:00 DBG] FileFinderStep Input [excludeDirectories]:
[17:16:00 DBG] FileFinderStep Input [searchFileName]: 'Unit.cs'
[17:16:00 DBG] FileFinderStep Input [errorIfNotFound]: 'True'
[17:16:00 DBG] FileFinderStep Output [filePathName]: Found file: 'D:\Temp\VSProjects\TodoApp\src\TodoApp.Domain\Units\Unit.cs', stored in parameter: 'FileFinderResult'
[17:16:00 DBG] EntityParserStep Input [entityFile]: 'D:\Temp\VSProjects\TodoApp\src\TodoApp.Domain\Units\Unit.cs'
[17:16:00 DBG] EntityParserStep Output [entityInfo]: 'EasyAbp.AbpHelper.Core.Models.EntityInfo'
[17:16:00 DBG] BuildDtoInfoStep Output [dtoInfo]: 'EasyAbp.AbpHelper.Core.Models.DtoInfo'
[17:16:00 DBG] EntityConstructorsStep Input [file]: 'D:\Temp\VSProjects\TodoApp\src\TodoApp.Domain\Units\Unit.cs'
[17:16:00 DBG] EntityConstructorsStep Output [modifications]: Modifications count: 0
[17:16:00 DBG] FileModifierStep Input [targetFile]: 'D:\Temp\VSProjects\TodoApp\src\TodoApp.Domain\Units\Unit.cs'
[17:16:00 DBG] FileModifierStep Input [modifications]: Modifications count: 0
[17:16:00 DBG] TextGenerationStep Input [templateDir]: '/Templates/Crud'
[17:16:00 DBG] TextGenerationStep Input [TemplateName]: 'UsingEntityNamespace'
[17:16:00 DBG] TextGenerationStep Input [model]: '{ ProjectInfo = BaseDirectory: D:\Temp\VSProjects\TodoApp, FullName: TodoApp, Name: TodoApp, TemplateType: Application, UiFramework: RazorPages, Tiered: False, Option = EasyAbp.AbpHelper.Core.Commands.Generate.Crud.CrudCommandOption, EntityInfo = EasyAbp.AbpHelper.Core.Models.EntityInfo, InterfaceInfo = , ClassInfo = , Bag = System.Dynamic.ExpandoObject, DtoInfo = EasyAbp.AbpHelper.Core.Models.DtoInfo }'
[17:16:00 DBG] TextGenerationStep Input [GeneratedTextKey]: 'EntityUsingText'
[17:16:00 DBG] TextGenerationStep Output [text]: Length: 23
[17:16:00 DBG] TextGenerationStep Input [templateDir]: '/Templates/Crud'
[17:16:00 DBG] TextGenerationStep Input [TemplateName]: 'UsingEntityDtoNamespace'
[17:16:00 DBG] TextGenerationStep Input [model]: '{ ProjectInfo = BaseDirectory: D:\Temp\VSProjects\TodoApp, FullName: TodoApp, Name: TodoApp, TemplateType: Application, UiFramework: RazorPages, Tiered: False, Option = EasyAbp.AbpHelper.Core.Commands.Generate.Crud.CrudCommandOption, EntityInfo = EasyAbp.AbpHelper.Core.Models.EntityInfo, InterfaceInfo = , ClassInfo = , Bag = System.Dynamic.ExpandoObject, DtoInfo = EasyAbp.AbpHelper.Core.Models.DtoInfo }'
[17:16:00 DBG] TextGenerationStep Input [GeneratedTextKey]: 'EntityDtoUsingText'
[17:16:00 DBG] TextGenerationStep Output [text]: Length: 28
[17:16:00 DBG] FileFinderStep Input [baseDirectory]: 'D:\Temp\VSProjects\TodoApp'
[17:16:00 DBG] FileFinderStep Input [excludeDirectories]:
[17:16:00 DBG] FileFinderStep Input [searchFileName]: 'TodoAppDbContext.cs'
[17:16:00 DBG] FileFinderStep Input [errorIfNotFound]: 'True'
[17:16:01 DBG] FileFinderStep Output [filePathName]: Found file: 'D:\Temp\VSProjects\TodoApp\src\TodoApp.EntityFrameworkCore\EntityFrameworkCore\TodoAppDbContext.cs', stored in parameter: 'FileFinderResult'
[17:16:01 DBG] DbContextClassStep Input [file]: 'D:\Temp\VSProjects\TodoApp\src\TodoApp.EntityFrameworkCore\EntityFrameworkCore\TodoAppDbContext.cs'
[17:16:01 DBG] DbContextClassStep Output [modifications]: Modifications count: 0
[17:16:01 DBG] FileModifierStep Input [targetFile]: 'D:\Temp\VSProjects\TodoApp\src\TodoApp.EntityFrameworkCore\EntityFrameworkCore\TodoAppDbContext.cs'
[17:16:01 DBG] FileModifierStep Input [modifications]: Modifications count: 0
[17:16:01 DBG] FileFinderStep Input [baseDirectory]: 'D:\Temp\VSProjects\TodoApp'
[17:16:01 DBG] FileFinderStep Input [excludeDirectories]:
[17:16:01 DBG] FileFinderStep Input [searchFileName]: 'TodoAppDbContextModelCreatingExtensions.cs'
[17:16:01 DBG] FileFinderStep Input [errorIfNotFound]: 'True'
[17:16:01 ERR] Error while invoking activity activity-23 of workflow 795a7c62d3c842d7be052491704f6dc1
System.IO.FileNotFoundException: TodoAppDbContextModelCreatingExtensions.cs
   at EasyAbp.AbpHelper.Core.Steps.Common.FileFinderStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in D:\a\AbpHelper.CLI\AbpHelper.CLI\src\AbpHelper.Core\Steps\Common\FileFinderStep.cs:line 54
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
[17:16:01 ERR] Error activity: {
  "SearchFileName": {
    "Syntax": "JavaScript",
    "Expression": "`${ProjectInfo.Name}DbContextModelCreatingExtensions.cs`",
    "Type": "System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
  },
  "Name": "DbContextModel"
}
`

**Comment by desconfiado** [comment]
The issue above also happens with dbp 4.3.0 and helper 0.8.1.
Can anyone help with this?

**Comment by Vayth** [comment]
For a workaround until this is fixed, you can copy `${ProjectInfo.Name}DbContextModelCreatingExtensions.cs` file created with 4.3 template, then paste it to EntityFrameworkCore project. You will need some adjustment in db context and may delete it once you don't use it anymore, but at least the other files are created successfully.

**Comment by wakuflair** [comment]
Please try the latest [v0.8.3 version](https://github.com/EasyAbp/AbpHelper.CLI/releases/tag/0.8.3)
