### ISSUE TITLE
install modules error

### ISSUE THREAD

**Issue by indexlang** [EasyAbp/AbpHelper.CLI#206]
when I use Abphelper GUI install easyabp module ,if there is a module folder in the solution path，the module folder have a module A，then install a easyabp module from gui，then  the error happen,maybe you can add search exclude path like Generate CRUD code page.
2023-02-10 09:09:50.210 +08:00 [ERR] Error while invoking activity activity-5 of workflow 05029e995ae74d36a60d6f7156b2ed01
System.IO.FileNotFoundException: The solution file 'A.sln' is not found in 'H:\aspnet-core'. Make sure you specific the right folder.
   at EasyAbp.AbpHelper.Core.Steps.Abp.ProjectInfoProviderStep.EnsureSlnFileExists(WorkflowExecutionContext context, String projectName) in D:\Projects\EasyAbp\EasyAbp.AbpHelper.GUI\AbpHelper.CLI\src\AbpHelper.Core\Steps\Abp\ProjectInfoProviderStep.cs:line 94
   at EasyAbp.AbpHelper.Core.Steps.Abp.ProjectInfoProviderStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in D:\Projects\EasyAbp\EasyAbp.AbpHelper.GUI\AbpHelper.CLI\src\AbpHelper.Core\Steps\Abp\ProjectInfoProviderStep.cs:line 71
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
2023-02-10 09:09:50.211 +08:00 [ERR] Error activity: {
  "Name": null
}

**Comment by gdlcf88** [comment]
See https://github.com/EasyAbp/AbpHelper.CLI/pull/207
