### ISSUE TITLE
Unknown ABP project structure

### ISSUE THREAD

**Issue by zyknow** [EasyAbp/AbpHelper.CLI#213]
i using abphelper on my microservice project to create crud,but i got error
============
### this is error and command info

(base) PS G:\AbpMicroservice\ms\src\services\product> abphelper generate crud Student -d G:\AbpMicroservice\ms\src\services\product --skip-db-migrations --skip-permissions --skip-get-list-input-dto --separate-dto --entity-prefix-dto --skip-ui --skip-view-model --skip-localization --skip-test --skip-entity-constructors
[15:49:24 INF] Use directory: `G:\AbpMicroservice\ms\src\services\product`
[15:49:24 INF] Command 'crud' started.
[15:49:24 DBG] ProjectInfoProviderStep Input [baseDirectory]: 'G:\AbpMicroservice\ms\src\services\product'
[15:49:24 DBG] ProjectInfoProviderStep Input [projectName]: ''
[15:49:24 DBG] ProjectInfoProviderStep Input [excludeDirectories]:
[15:49:24 ERR] Error while invoking activity activity-5 of workflow 1a7554fc61a9433496dd9d6cf81e87f8
System.NotSupportedException: Unknown ABP project structure. Directory: G:\AbpMicroservice\ms\src\services\product
   at EasyAbp.AbpHelper.Core.Steps.Abp.ProjectInfoProviderStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in /home/runner/work/AbpHelper.CLI/AbpHelper.CLI/src/AbpHelper.Core/Steps/Abp/ProjectInfoProviderStep.cs:line 35
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
[15:49:24 ERR] Error activity: {
  "Name": null
}

### this is  my product service files structure

G:.
├─.idea
│  └─.idea.AbpMicroservice.ProductService
│      └─.idea
├─.template.config
├─src
│  ├─AbpMicroservice.ProductService.Application
│  │  ├─Products
│  │  └─Properties
│  ├─AbpMicroservice.ProductService.Application.Contracts
│  │  ├─Permissions
│  │  └─Products
│  ├─AbpMicroservice.ProductService.Domain
│  │  ├─Products
│  │  ├─Properties
│  │  ├─Settings
│  │  └─Students
│  ├─AbpMicroservice.ProductService.Domain.Shared
│  │  └─Localization
│  │      └─ProductService
│  ├─AbpMicroservice.ProductService.EntityFrameworkCore
│  │  ├─EntityFrameworkCore
│  │  ├─Migrations
│  │  └─Properties
│  ├─AbpMicroservice.ProductService.HttpApi
│  ├─AbpMicroservice.ProductService.HttpApi.Client
│  └─AbpMicroservice.ProductService.HttpApi.Host
│      ├─Controllers
│      ├─DbMigrations
│      ├─Properties
│      └─wwwroot
└─test
    ├─AbpMicroservice.ProductService.Application.Tests
    │  └─Products
    ├─AbpMicroservice.ProductService.Domain.Tests
    │  └─Samples
    ├─AbpMicroservice.ProductService.EntityFrameworkCore.Tests
    │  └─EntityFrameworkCore
    │      └─Products
    └─AbpMicroservice.ProductService.TestBase
        └─Security

**Comment by gdlcf88** [comment]
The CRUD generator was designed and validated for the normal app/module startup template, but it usually works for multi-module project structures as well. If your project structure is more complex, try debugging the AbpHelper CLI.

**Comment by zyknow** [comment]
i find the error code is 

![image](https://user-images.githubusercontent.com/49929368/234223503-10fa3606-aeec-4f10-afd1-b4464a4c1f2d.png)

when i change code to this ,it's work and my microservice project can successful build
![image](https://user-images.githubusercontent.com/49929368/234224038-0a4648cd-59bd-40d8-a23d-2d6568b540ec.png)

even i change the input args to this ,also my microservice project can successful build
![image](https://user-images.githubusercontent.com/49929368/234224480-98f0631b-28b4-4128-982f-62f518d7fd23.png)

so ,i think this code can be motify to better validation this project it's a `TemplateType.Application ?`  

``` cs 
if (FileExistsInDirectory(baseDirectory, "*.Host.Shared.csproj", excludeDirectories) || FileExistsInDirectory(baseDirectory, "*.Installer.csproj", excludeDirectories))
            {
                templateType = TemplateType.Module;
            }
```

**Comment by gdlcf88** [comment]
Could you please try to improve it?

**Comment by zyknow** [comment]
yeah , sure , i have question for this code 
``` cs 
if (FileExistsInDirectory(baseDirectory, "*.Host.Shared.csproj", excludeDirectories) || FileExistsInDirectory(baseDirectory, "*.Installer.csproj", excludeDirectories))
            {
                templateType = TemplateType.Module;
            }
```
why comparison  *.Host.Shared.csproj and *.Installer.csproj in base directory, look like don't have this files on use abp cli create template project

**Comment by gdlcf88** [comment]
This is a part of the module template, which is different from the app template.

**Comment by zyknow** [comment]
yeah,i find i provide error code on previous conversation
should be this code to effect it's `TemplateType.Application`
![image](https://user-images.githubusercontent.com/49929368/234229501-16efabb9-4fff-4d76-bfcc-09c5d98bc19e.png)

it's could be another obvious different on abp `Module` and `Application` template

**Comment by zyknow** [comment]
so, for easily , it's to add new `else if` to add new condition to equal it's `TemplateType.Application`

**Comment by zyknow** [comment]
and i think this condition `else if (FileExistsInDirectory(baseDirectory, "*.DbMigrator.csproj", excludeDirectories))` ,it's to ensure this project is `multi layer and abp project` ?
