### ISSUE TITLE
CRUD operation faced with error

### ISSUE THREAD

**Issue by naderjavid** [EasyAbp/AbpHelper.CLI#238]
after running below command
`abphelper generate crud Todo -d C:\src\temp`
i got this error

[12:46:49 DBG] Build started...
[12:46:59 DBG] Build failed. Use dotnet build to see the errors.
[12:46:59 ERR] Error while invoking activity activity-91 of workflow 0975d5a3c21b4d7db18ceeba7b1e63ff
EasyAbp.AbpHelper.Core.Steps.Common.RunningCommandFailedException: Exception of type 'EasyAbp.AbpHelper.Core.Steps.Common.RunningCommandFailedException' was thrown.
   at EasyAbp.AbpHelper.Core.Steps.Common.RunCommandStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in /home/runner/work/AbpHelper.CLI/AbpHelper.CLI/src/AbpHelper.Core/Steps/Common/RunCommandStep.cs:line 26
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
[12:46:59 ERR] Error activity: {
  "Command": {
    "Syntax": "JavaScript",
    "Expression": "`dotnet ef migrations add Added${EntityInfo.Name} -p \"${MigrationProjectFile}\" -s \"${StartupProjectFile}\"`",
    "Type": "System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
  },
  "Name": "AddMigration"
}

**Comment by naderjavid** [comment]
### we have error in test part too
![image](https://github.com/EasyAbp/AbpHelper.CLI/assets/30950912/9a7dfc84-b751-4ec8-8ccf-2d776fed02ca)

### based on project sample it should be like
![image](https://github.com/EasyAbp/AbpHelper.CLI/assets/30950912/75d0f5e9-4a37-4e3c-9411-c1caa40e92d5)

**Comment by naderjavid** [comment]
i fixed errors with [pull request 239](https://github.com/EasyAbp/AbpHelper.CLI/pull/239)
