### ISSUE TITLE
System.NotSupportedException: Unknown ABP project structure. Directory

### ISSUE THREAD

**Issue by xewn** [EasyAbp/AbpHelper.CLI#26]
[10:32:12 ERR] Error while invoking activity activity-5 of workflow 713380c7ffff471cb26237e68d68cf37
System.NotSupportedException: Unknown ABP project structure. Directory: D:\Work\Hd.StandardWork.Exec
   at EasyAbp.AbpHelper.Steps.Abp.ProjectInfoProviderStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in D:\Repos\EasyAbp\AbpHelper.CLI\src\AbpHelper\Steps\Abp\ProjectInfoProviderStep.cs:line 36
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)

我是用abp 创建的模块，2.2.1版本的。

**Comment by wakuflair** [comment]
Is "D:\Work\Hd.StandardWork.Exec" the **root** directory of your ABP project?

**Comment by wakuflair** [comment]
We confirmed that this is because the template structure has changed in ABP v2.2.1, we will release AbpHelper v0.1.2(today) to support ABP v2.2.1 .

**Comment by gdlcf88** [comment]
AbpHelper CLI v0.1.2 just released, can you try again? @xewn

**Comment by xewn** [comment]
OK,Thanks

**Comment by wakuflair** [comment]
> OK,Thanks

Is everything fine now?
