### ISSUE TITLE
free abp , Localization isssue

### ISSUE THREAD

**Issue by mrs01dev** [EasyAbp/AbpHelper.CLI#69]
Dear all 

AbpHelper.CLI have an issue when using free abp .
note : i had replaced solution directory with letter "~"
[20:05:16 ERR] Error while invoking activity activity-42 of workflow cd8d92f751064887856130b5b26ef52f
System.IO.DirectoryNotFoundException: Could not find a part of the path '~.WebUI.Domain.Shared\Localization'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at EasyAbp.AbpHelper.Steps.Common.MultiFileFinderStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in D:\Repos\EasyAbp\AbpHelper.CLI\src\AbpHelper\Steps\Common\MultiFilesFinderStep.cs:line 42
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)

Best regards

**Comment by mrs01dev** [comment]
Dear all,

The issue cause was using the path of  directory which have the Visual Studio solution file ".sln".

Thanks
