### ISSUE TITLE
Error With version ABP 2.9

### ISSUE THREAD

**Issue by ecaceresds** [EasyAbp/AbpHelper.CLI#74]
Trying to generate with abphelper generate command.

[09:09:00 DBG] Build started...
[09:09:10 DBG] Build failed.
[09:09:10 ERR] Error while invoking activity activity-70 of workflow 537665ca021542e38ba6ef953f939246
EasyAbp.AbpHelper.Steps.Common.RunningCommandFailedException: Exception of type 'EasyAbp.AbpHelper.Steps.Common.RunningCommandFailedException' was thrown.
   at EasyAbp.AbpHelper.Steps.Common.RunCommandStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in D:\Repos\EasyAbp\AbpHelper.CLI\src\AbpHelper\Steps\Common\RunCommandStep.cs:line 28
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)

C:\Users\UserName>

**Comment by wakuflair** [comment]
"Build failed" menas there're compile errors, maybe some code generated uncorrectly.
You can build your project to see the errors.

**Comment by ecaceresds** [comment]
Thanks wakuflair,

There was no compilation error before trying to generate Todo example. The helper was generating correctly before the updates of abp to 2.9 and the new version of abphelper. 

I'm using abphelper 0.4.2 and ABP 2.9.

**Comment by ecaceresds** [comment]
I've found the Issue.
There is a problem with the version 2.9 of ABP and the abphelper. 

The project *.Domain.Shared is not being include , when you generate with "abp new MyProject" (should be included).

We manually to fixed the UI location namespace and run the abphelper command without generate the UI.
